apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: cms-xcache-nano
  name: cms-xcache-bcache-1-nano-ucsd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cms-xcache-nano
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: cms-xcache-nano
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - bcache-1.t2.ucsd.edu
      containers:
      - env:
        - name: XC_SITE
          value: UCSD-XCACHE-NANO
        - name: XC_RAMSIZE
          value: 24g
        image: opensciencegrid/cms-xcache:fresh
        imagePullPolicy: Always
        name: cms-xcache-bcache-1-nano-ucsd
        resources:
           limits:
              memory: 24Gi
              cpu: 6
           requests:
              memory: 18Gi
              cpu: 3
        volumeMounts:
        - mountPath: /etc/osg/image-config.d/00-create-dirs.sh
          name: configinit
          subPath: 00-create-dirs.sh
        - mountPath: /etc/xrootd/config.d/90-node-xcache-nano-disks.cfg
          name: config90
          subPath: 90-node-xcache-nano-disks.cfg
        - mountPath: /etc/xrootd/config.d/95-local-nano-ucsd.cfg
          name: config95
          subPath: 95-local-ucsd.cfg
        - mountPath: /etc/grid-security/hostcert.pem
          name: hostcert
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
        - mountPath: /xcache-root
          name: localroot
        - mountPath: /data45
          name: data45
        - mountPath: /data46
          name: data46
        - mountPath: /data47
          name: data47
        - mountPath: /data48
          name: data48
          dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: 00-create-dirs.sh
            path: 00-create-dirs.sh
          name: cms-xcache-nano
        name: configinit
      - configMap:
          defaultMode: 420
          items:
          - key: 90-node-disks.cfg
            path: 90-node-disks.cfg
          name: cms-xcache-nano
        name: config90
      - configMap:
          defaultMode: 420
          items:
          - key: 95-local-ucsd.cfg
            path: 95-local-ucsd.cfg
          name: cms-xcache-nano
        name: config95
      - hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
        name: hostcert
      - hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
        name: hostkey
      - name: localroot
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s45
       - name: data45
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s45
      - name: data46
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s46
     - name: data47
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s47
      - name: data48
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s48
